# Site settings
title:          Elastropy Blog
description:    "Turning data into compelling stories"
baseurl:        "/epyblog"
url:            "https://tbkopen.github.io"

# Google Analytics
# google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Elastropy Team
  url:          www.elastropy.com
  email:        elastropy@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ 
  Gemfile, 
  Gemfile.lock, 
  tale.gemspec, 
  README.md, 
  .gitignore, 
  LICENSE, 
  .github/,
  ]

# Disqus (Set to your disqus id)
# disqus:         jekyll-tale